//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Administrador
{
    public int idAdministrador { get; set; }
    public string Rut { get; set; }
    public string Primer_nombre { get; set; }
    public string Segundo_nombre { get; set; }
    public string Apellido_materno { get; set; }
    public string Apellido_paterno { get; set; }
    public string Calle { get; set; }
    public string Numero_calle { get; set; }
    public string Password { get; set; }
}

public partial class Banco
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Banco()
    {
        this.Usuario = new HashSet<Usuario>();
    }

    public int idBanco { get; set; }
    public string Nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Usuario> Usuario { get; set; }
}

public partial class Comuna
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Comuna()
    {
        this.Usuario = new HashSet<Usuario>();
    }

    public int idComuna { get; set; }
    public string Nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Usuario> Usuario { get; set; }
}

public partial class Desvio
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Desvio()
    {
        this.Telefono = new HashSet<Telefono>();
    }

    public int idDesvio { get; set; }
    public bool Estado { get; set; }
    public Nullable<long> idTelefonoDesviador { get; set; }
    public Nullable<long> idTelefonoDesviado { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Telefono> Telefono { get; set; }
}

public partial class Historial
{
    public long idHistorial { get; set; }
    public Nullable<long> Uso_terminal { get; set; }
    public Nullable<System.DateTime> Fecha { get; set; }
    public Nullable<long> ID_Terminal_movil { get; set; }
}

public partial class Mensaje
{
    public long idMensaje { get; set; }
    public string Contenido { get; set; }
    public long idTelefonoEmisor { get; set; }
    public long idTelefonoReceptor { get; set; }
    public long idTarifa { get; set; }

    public virtual Tarifa Tarifa { get; set; }
}

public partial class Recarga
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Recarga()
    {
        this.Transbank = new HashSet<Transbank>();
    }

    public long idRecarga { get; set; }
    public System.DateTime Fecha { get; set; }
    public long Monto { get; set; }
    public string Numero { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Transbank> Transbank { get; set; }
}

public partial class Region
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Region()
    {
        this.Usuario = new HashSet<Usuario>();
    }

    public int idRegion { get; set; }
    public string Nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Usuario> Usuario { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Tarifa
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tarifa()
    {
        this.Mensaje = new HashSet<Mensaje>();
    }

    public long idTarifa { get; set; }
    public int Costo { get; set; }
    public System.DateTime Fecha { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Mensaje> Mensaje { get; set; }
}

public partial class Telefono
{
    public long Identificador { get; set; }
    public string Numero { get; set; }
    public bool EstadoConexion { get; set; }
    public int Saldo { get; set; }
    public long idUsuario { get; set; }
    public int idDesvio { get; set; }

    public virtual Desvio Desvio { get; set; }
    public virtual Usuario Usuario { get; set; }
}

public partial class Transbank
{
    public long ID_Transbank { get; set; }
    public string Numero_operacion { get; set; }
    public System.DateTime Fecha_operacion { get; set; }
    public long Monto { get; set; }
    public long ID_Recarga { get; set; }

    public virtual Recarga Recarga { get; set; }
}

public partial class Usuario
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Usuario()
    {
        this.Telefono = new HashSet<Telefono>();
    }

    public long idUsuario { get; set; }
    public string Rut { get; set; }
    public string Primer_nombre { get; set; }
    public string Segundo_nombre { get; set; }
    public string Apellido_materno { get; set; }
    public string Apellido_paterno { get; set; }
    public string Calle { get; set; }
    public string Numero_domicilio { get; set; }
    public int Banco { get; set; }
    public int Comuna { get; set; }
    public int Region { get; set; }

    public virtual Banco Banco1 { get; set; }
    public virtual Comuna Comuna1 { get; set; }
    public virtual Region Region1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Telefono> Telefono { get; set; }
}

public partial class pa_listarComunas_Result
{
    public int idComuna { get; set; }
    public string Nombre { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
